### PR TITLE
Add logic to load the app from a configured dist location if present.

### LINKED ISSUE #60: Deployment fails to find module when upgrading from v1.7.5 to v2.0.3
I wasn't specifying a version for the component in the serverless.yml file and when I deployed, I pulled in the latest version of the component and ran into the following error:

```
Error: Cannot find module '..'
Require stack:
- /var/task/_express/handler.js
- /var/task/_serverless/handler.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/_express/handler.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

When I compared the 2 deployment packages (the last known working version and the latest that failed), I noticed the version difference and was able to resolve the issue by rolling back to 1.7.5 by specifying the version in my component property in the serverless.yml file.

The deployment packages look the same at a glance, and my application was bundled/packaged the same in both cases. 

The @serverless/platform-client version went from 1.1.6 to 3.8.0 which was interesting but it's hard to tell exactly what is different between the 2 deployments.

I'm happy to provide more information, I'm just not sure what would be useful, but I wanted to report this as an issue.

### PR DESCRIPTION
**Pull request by Cameron-C-Chapman**
Resolves #60 

I'm still having issues with deploying from a dist folder so I thought I'd give a fix a try. Just looking at the code it seems like this might do it.

I haven't actually got to test this with a real deployment yet. It seems like just using the integration tests is the easiest way to do that. Is there any reason I can't/shouldn't just provide some AWS credentials locally for a personal AWS account and run the integration test to give it a shot? I'm not sure the best way to setup the folder structure specific to this use case but generic to the integration tests, I'm open to opinions/thoughts there.

### CODE REVIEW

**Comment by Cameron-C-Chapman** [comment]
This ended up not being the issue. The conversation in #60 includes what was done to resolve the issue I was seeing.
