### ISSUE TITLE
Deployment fails to find module when upgrading from v1.7.5 to v2.0.3

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [serverless-components/express#60]
I wasn't specifying a version for the component in the serverless.yml file and when I deployed, I pulled in the latest version of the component and ran into the following error:

```
Error: Cannot find module '..'
Require stack:
- /var/task/_express/handler.js
- /var/task/_serverless/handler.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/_express/handler.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

When I compared the 2 deployment packages (the last known working version and the latest that failed), I noticed the version difference and was able to resolve the issue by rolling back to 1.7.5 by specifying the version in my component property in the serverless.yml file.

The deployment packages look the same at a glance, and my application was bundled/packaged the same in both cases. 

The @serverless/platform-client version went from 1.1.6 to 3.8.0 which was interesting but it's hard to tell exactly what is different between the 2 deployments.

I'm happy to provide more information, I'm just not sure what would be useful, but I wanted to report this as an issue.

**Comment by eahefnawy** [comment]
Thanks @Cameron-C-Chapman ... does your package.json has a `main: app.js` property?

**Comment by freddieerg** [comment]
Wow this is exactly what happened to me. I could have saved myself hours by checking the issues page :( 

Can someone please explain whats happened here because since 2.0.3 I just cannot get my application to work!

**Comment by freddieerg** [comment]
> Thanks @Cameron-C-Chapman ... does your package.json has a `main: app.js` property?

Ok so judging by what you're saying the v2.0.3 update actually now checks your package.json for the main entry instead of what it did previously which was to force entry as app.js at the root directory, is this whats happened?

**Comment by eahefnawy** [comment]
@freddieerg yep that's right

**Comment by Cameron-C-Chapman** [comment]
> Thanks @Cameron-C-Chapman ... does your package.json has a `main: app.js` property?

I do have the `main` property set to `app.js` in my package.json. I have a build process that builds the app and places it in a `dist` folder instead of the root folder.

Here is my `input:src` setting in the `serverelss.yml` file:
```
src:
    src: ./
    hook: npm run build
    dist: ./dist/
```

The dist folder output just contains an `app.js` and an `app.js.map` file.

![image](https://user-images.githubusercontent.com/1323581/108077714-721b4e80-7032-11eb-899a-6ee38ce5bafc.png)

Should I tweak the package.json or the dist configuration at all?

**Comment by freddieerg** [comment]
> @freddieerg yep that's right

Thank you! This was a much needed change IMO! :)

**Comment by rrooding** [comment]
I'm using Nx.dev and so I only have one package.json at the top level of the project containing many apps and libraries. Any way I can fix this issue in another way?

EDIT:
I fixed this by using the [generate-package-json-webpack-plugin](https://www.npmjs.com/package/generate-package-json-webpack-plugin) to generate a single specific package.json in the `dist` directory during the build.

**Comment by servoice** [comment]
I am running into the same problem. Everything works fine locally and this seems to be the issue when deployed: 
![Screen Shot 2021-02-17 at 5 52 33 PM](https://user-images.githubusercontent.com/63298247/108278540-2f986580-7149-11eb-9a09-0d8c64ab4220.png)

serverless.yml 
`inputs:
  src:
    src: ./
    hook: npm run build
    dist: ./build
`

webpack.config
`const path = require('path');
const nodeExternals = require('webpack-node-externals');
module.exports = {
  entry: './app.js',
  mode: 'production',
  target: 'node',
  externals: [nodeExternals()],
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, 'build'),
    filename: 'app.js',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [['env', { targets: { node: '12.17' } }]],
            },
          },
        ],
      },
    ],
  },
};`

package.json
`"main": "app.js",
  "dependencies": {
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dayjs": "^1.10.4",
    "express": "^4.17.1",
    "helmet": "^4.4.1",
    "ioredis": "^4.22.0",
    "jwt-decode": "^3.1.2",
    "nanoid": "^3.1.20",
    "stripe": "^8.135.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/node": "^7.12.16",
    "@babel/preset-env": "^7.12.16",
    "babel-loader": "^8.2.2",
    "babel-preset-env": "^1.7.0",
    "eslint": "^7.20.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "nodemon": "^2.0.7",
    "serverless-domain-manager": "^5.1.0",
    "webpack": "^5.22.0",
    "webpack-cli": "^4.5.0",
    "webpack-node-externals": "^2.5.2"
  },
  "scripts": {
    "start": "nodemon build/app.js",
    "build": "webpack --config ./webpack.config.js --mode production",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}`

**Comment by yosefcevallos** [comment]
@Cameron-C-Chapman how did you fix this? I'm trying to setup a new service using:

`create --template-url https://github.com/serverless-components/express/tree/master/templates/express-starter-typescript-webpack --path service`

I noticed the difference between the `express-starter` template and the `express-starter-typescript-tsc` and `express-starter-typescript-webpack` was the latter didn't have the `main: app.js` property in package.json @eahefnawy described.

I updated my package.json to have `main: app.js` but still getting the same error you're getting:

`
Error: Cannot find module '..'
Require stack:
- /var/task/_express/handler.js
- /var/task/_serverless/handler.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/_express/handler.js:16:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
`

Anyways, any help on this would be great!

**Comment by yosefcevallos** [comment]
UPDATE

This fixed it:

https://github.com/serverless-components/express/issues/12#issuecomment-695839017

**Comment by Cameron-C-Chapman** [comment]
@albertocevallos I can't track down any change that would indicate this but for some reason the pre v2 version of this component seemed to honor a `dist` directory but not the post v2.

I also can't find any evidence that the `dist` configuration was ever explicitly accounted for, but the typescript template you are referring to has that set, and my current app that has the compiled app.js put in a dist folder and used that config worked before as well.

I have the main property set, it seems to just not be loading the app from the dist folder, but instead trying to load it from the src folder. 

Again, this was working for me before with no changes on my end. My config is just like the comment you linked to, but using parcel instead of webpack.

I was thinking it might have to do with not looking in the configured dist folder and gave a fix a stab, #61, but maybe it has to do with node_modules no longer copying or being found like they were in a pre v2 version?

**Comment by yosefcevallos** [comment]
@Cameron-C-Chapman I'd suggest trying webpack instead, unless there's a specific reason to use Parcel (cache?).

And then using https://github.com/serverless-components/express/issues/12#issuecomment-695839017 and replacing `dist` with `build` .

**Comment by Cameron-C-Chapman** [comment]
@albertocevallos I finally got back to this and got it to work using the suggestions in this and the various linked threads 🎉 

Thanks for helping me through that 😄 

I'll go ahead and close this issue.
